// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelDownload():Promise<void>;

export function GetSetupState():Promise<main.SetupState>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function LoadSettings():Promise<main.Settings>;

export function OpenAndTranscribeFile(arg1:main.Settings):Promise<string>;

export function Refine(arg1:string,arg2:main.Settings):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function StartDownload(arg1:string):Promise<void>;

export function Transcribe(arg1:string,arg2:string,arg3:main.Settings):Promise<string>;
