// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function GetSetupState() {
  return window['go']['main']['App']['GetSetupState']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function Refine(arg1, arg2) {
  return window['go']['main']['App']['Refine'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function Transcribe(arg1, arg2, arg3) {
  return window['go']['main']['App']['Transcribe'](arg1, arg2, arg3);
}
